#!/bin/bash

set -euo pipefail

project="serde"
appContainer="php-fpm"

function build {
    docker compose build
}

function start {
    docker compose up -d
}

function stop {
    docker compose down
}

function restart {
  stop
  start
}

function shell {
  start
  docker compose exec -it -u $(id -u):$(id -g) ${appContainer} bash
}

function default {
    start
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
