---
name: PHPUnit tests
on:
    push: ~
    pull_request: ~

jobs:
    phpunit:
        name: PHPUnit tests on ${{ matrix.php }} ${{ matrix.composer-flags }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.1', '8.2' ]
                composer-flags: [ '' ]
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: pcov
                  tools: composer:v2
            - run: composer update --no-progress ${{ matrix.composer-flags }}
            - run: composer coverage
